# Generated by Django 2.0.3 on 2018-03-24 02:39

import courses.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_field_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=courses.field.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=courses.field.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
